title: Josh and the blog
author: onlinejoshdean
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
   I am going to post some ideas that I have gathered from stuff I have read recently. 
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
